# Assignment: Compresive Strength Concrete Problem


### Abstract: 

Concrete is the most important material in civil engineering. The concrete compressive strength (concrete strength to bear the load) is a highly nonlinear function of age and ingredients.  <br><br>

<table border="1"  cellpadding="6" bordercolor="red">
	<tbody>
        <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Data Set Characteristics:&nbsp;&nbsp;</b></p></td>
		<td><p class="normal">Multivariate</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Instances:</b></p></td>
		<td><p class="normal">1030</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Area:</b></p></td>
		<td><p class="normal">Physical</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">
    <tbody>
        <tr>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Attribute Characteristics:</b></p></td>
            <td><p class="normal">Real</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Number of Attributes:</b></p></td>
            <td><p class="normal">9</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Date Donated</b></p></td>
            <td><p class="normal">2007-08-03</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">	
    <tbody>
    <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Associated Tasks:</b></p></td>
		<td><p class="normal">Regression</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Missing Values?</b></p></td>
		<td><p class="normal">N/A</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Web Hits:</b></p></td>
		<td><p class="normal">231464</p></td>
	</tr>
    </tbody>
    </table>

###  Description:
| Features Name | Data Type | Measurement | Description |
| -- | -- | -- | -- |
Cement (component 1) | quantitative | kg in a m3 mixture | Input Variable
Blast Furnace Slag (component 2) | quantitative | kg in a m3 mixture | Input Variable
Fly Ash (component 3) | quantitative | kg in a m3 mixture | Input Variable
Water (component 4) | quantitative | kg in a m3 mixture | Input Variable
Superplasticizer (component 5) | quantitative | kg in a m3 mixture | Input Variable
Coarse Aggregate (component 6) | quantitative | kg in a m3 mixture | Input Variable
Fine Aggregate (component 7) | quantitative | kg in a m3 mixture | Input Variable
Age | quantitative | Day (1~365) | Input Variable
Concrete compressive strength | quantitative | MPa | Output Variable

### WORKFLOW :
- Load Data
- Check Missing Values ( If Exist ; Fill each record with mean of its feature )
- Standardized the Input Variables. **Hint**: Centeralized the data
- Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).
- Model : input Layer (No. of features ), 3 hidden layers including 10,8,6 unit & Output Layer with activation function relu/tanh (check by experiment).
- Compilation Step (Note : Its a Regression problem , select loss , metrics according to it)
- Train the Model with Epochs (100) and validate it
- If the model gets overfit tune your model by changing the units , No. of layers , activation function , epochs , add dropout layer or add Regularizer according to the need .
- Evaluation Step
- Prediction


# Load Data:
[Click Here to Download DataSet](https://github.com/ramsha275/ML_Datasets/blob/main/compresive_strength_concrete.csv)

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
import seaborn as sns
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam, SGD

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
data = pd.read_csv('/content/gdrive/MyDrive/compresive_strength_concrete.csv')

In [ ]:
data.shape

(1030, 9)

In [ ]:
data.head()

Cement (component 1)(kg in a m^3 mixture)  ...  Concrete compressive strength(MPa, megapascals) 
0                                      540.0  ...                                             79.99
1                                      540.0  ...                                             61.89
2                                      332.5  ...                                             40.27
3                                      332.5  ...                                             41.05
4                                      198.6  ...                                             44.30

[5 rows x 9 columns]

##Checking Missing Values ( If Exist ; Fill each record with mean of its feature )

In [ ]:
data.isnull().sum()

Cement (component 1)(kg in a m^3 mixture)                0
Blast Furnace Slag (component 2)(kg in a m^3 mixture)    0
Fly Ash (component 3)(kg in a m^3 mixture)               0
Water  (component 4)(kg in a m^3 mixture)                0
Superplasticizer (component 5)(kg in a m^3 mixture)      0
Coarse Aggregate  (component 6)(kg in a m^3 mixture)     0
Fine Aggregate (component 7)(kg in a m^3 mixture)        0
Age (day)                                                0
Concrete compressive strength(MPa, megapascals)          0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column                                                 Non-Null Count  Dtype  
---  ------                                                 --------------  -----  
 0   Cement (component 1)(kg in a m^3 mixture)              1030 non-null   float64
 1   Blast Furnace Slag (component 2)(kg in a m^3 mixture)  1030 non-null   float64
 2   Fly Ash (component 3)(kg in a m^3 mixture)             1030 non-null   float64
 3   Water  (component 4)(kg in a m^3 mixture)              1030 non-null   float64
 4   Superplasticizer (component 5)(kg in a m^3 mixture)    1030 non-null   float64
 5   Coarse Aggregate  (component 6)(kg in a m^3 mixture)   1030 non-null   float64
 6   Fine Aggregate (component 7)(kg in a m^3 mixture)      1030 non-null   float64
 7   Age (day)                                              1030 non-null   int64  
 8   Concrete compressive strength(MPa, megapascals)  

In [ ]:
# Separating Input and Output Colmumns 
X = data.iloc[:, :-1].values  # Input Columns
Y = data.iloc[:, -1:].values # Output Columns 

In [ ]:
X

array([[ 540. ,    0. ,    0. , ..., 1040. ,  676. ,   28. ],
       [ 540. ,    0. ,    0. , ..., 1055. ,  676. ,   28. ],
       [ 332.5,  142.5,    0. , ...,  932. ,  594. ,  270. ],
       ...,
       [ 148.5,  139.4,  108.6, ...,  892.4,  780. ,   28. ],
       [ 159.1,  186.7,    0. , ...,  989.6,  788.9,   28. ],
       [ 260.9,  100.5,   78.3, ...,  864.5,  761.5,   28. ]])

In [ ]:
Y

array([[79.99],
       [61.89],
       [40.27],
       ...,
       [23.7 ],
       [32.77],
       [32.4 ]])

# Splitting Data 
###Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).

In [ ]:
X.shape
x_train = X[:515,] # 50% Training 
x_test = X[515:824,] # 30% Test 
x_val = X[824:,] # 20% Validatation

y_train = Y[:515,] # 50% Training
y_test = Y[515:824,] # 30% Test
y_val = Y[824:,] # 20% Validataion


In [ ]:
print (x_train.shape, x_test.shape, x_val.shape)
print (y_train.shape, y_test.shape, y_val.shape)

(515, 8) (309, 8) (206, 8)
(515, 1) (309, 1) (206, 1)


# Standardization of Training / Test / Validation Data 

In [ ]:
mean = x_train.mean(axis=0)
x_train -= mean
std = x_train.std(axis=0)
x_train /= std


x_val -= mean
x_val /= std

x_test -= mean
x_test /= std



In [ ]:
print (x_train.shape, x_test.shape, x_val.shape)
print (y_train.shape, y_test.shape, y_val.shape)

(515, 8) (309, 8) (206, 8)
(515, 1) (309, 1) (206, 1)


# Setting up the model

In [ ]:
model = Sequential()
model.add(tf.keras.layers.Dense(10, activation='relu',input_shape=(8,)))
model.add(tf.keras.layers.Dense(8,))
model.add(tf.keras.layers.Dense(6,))
model.add(tf.keras.layers.Dense(1,))

# Model Compilation

In [ ]:
model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])

# Training

In [ ]:
history = model.fit(x_train, y_train,epochs=200, validation_data =(x_val, y_val))

Epoch 1/200
17/17 [==============================] - 1s 32ms/step - loss: 1978.3941 - mae: 41.0967 - val_loss: 1190.5719 - val_mae: 32.1185
Epoch 2/200
17/17 [==============================] - 0s 4ms/step - loss: 2096.3644 - mae: 42.3634 - val_loss: 1170.3099 - val_mae: 31.7838
Epoch 3/200
17/17 [==============================] - 0s 4ms/step - loss: 1957.0862 - mae: 40.8469 - val_loss: 1146.7654 - val_mae: 31.3909
Epoch 4/200
17/17 [==============================] - 0s 4ms/step - loss: 1919.9737 - mae: 40.2857 - val_loss: 1117.8638 - val_mae: 30.8973
Epoch 5/200
17/17 [==============================] - 0s 4ms/step - loss: 1960.6422 - mae: 40.6686 - val_loss: 1087.1042 - val_mae: 30.3563
Epoch 6/200
17/17 [==============================] - 0s 4ms/step - loss: 1879.4198 - mae: 39.4622 - val_loss: 1049.7415 - val_mae: 29.6907
Epoch 7/200
17/17 [==============================] - 0s 4ms/step - loss: 1803.1378 - mae: 38.4620 - val_loss: 1007.3506 - val_mae: 28.9111
Epoch 8/200
17/17 [=======

# Evaluation

In [ ]:

loss, mae = model.evaluate(x_test, y_test)


10/10 [==============================] - 0s 2ms/step - loss: 226.3324 - mae: 11.9764


In [ ]:
loss, mae

(226.33242797851562, 11.976364135742188)

In [ ]:
validation = model.evaluate(x_val, y_val)

7/7 [==============================] - 0s 2ms/step - loss: 224.5336 - mae: 11.9453


#Prediction

In [ ]:
pred = model.predict(x_test[0:5])
pred

array([[28.876652],
       [26.91268 ],
       [27.20274 ],
       [31.25849 ],
       [40.394703]], dtype=float32)