# Assignment: Compresive Strength Concrete Problem


### Abstract: 

Concrete is the most important material in civil engineering. The concrete compressive strength (concrete strength to bear the load) is a highly nonlinear function of age and ingredients.  <br><br>

<table border="1"  cellpadding="6" bordercolor="red">
	<tbody>
        <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Data Set Characteristics:&nbsp;&nbsp;</b></p></td>
		<td><p class="normal">Multivariate</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Instances:</b></p></td>
		<td><p class="normal">1030</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Area:</b></p></td>
		<td><p class="normal">Physical</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">
    <tbody>
        <tr>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Attribute Characteristics:</b></p></td>
            <td><p class="normal">Real</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Number of Attributes:</b></p></td>
            <td><p class="normal">9</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Date Donated</b></p></td>
            <td><p class="normal">2007-08-03</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">	
    <tbody>
    <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Associated Tasks:</b></p></td>
		<td><p class="normal">Regression</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Missing Values?</b></p></td>
		<td><p class="normal">N/A</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Web Hits:</b></p></td>
		<td><p class="normal">231464</p></td>
	</tr>
    </tbody>
    </table>

###  Description:
| Features Name | Data Type | Measurement | Description |
| -- | -- | -- | -- |
Cement (component 1) | quantitative | kg in a m3 mixture | Input Variable
Blast Furnace Slag (component 2) | quantitative | kg in a m3 mixture | Input Variable
Fly Ash (component 3) | quantitative | kg in a m3 mixture | Input Variable
Water (component 4) | quantitative | kg in a m3 mixture | Input Variable
Superplasticizer (component 5) | quantitative | kg in a m3 mixture | Input Variable
Coarse Aggregate (component 6) | quantitative | kg in a m3 mixture | Input Variable
Fine Aggregate (component 7) | quantitative | kg in a m3 mixture | Input Variable
Age | quantitative | Day (1~365) | Input Variable
Concrete compressive strength | quantitative | MPa | Output Variable

### WORKFLOW :
- Load Data
- Check Missing Values ( If Exist ; Fill each record with mean of its feature )
- Standardized the Input Variables. **Hint**: Centeralized the data
- Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).
- Model : input Layer (No. of features ), 3 hidden layers including 10,8,6 unit & Output Layer with activation function relu/tanh (check by experiment).
- Compilation Step (Note : Its a Regression problem , select loss , metrics according to it)
- Train the Model with Epochs (100) and validate it
- If the model gets overfit tune your model by changing the units , No. of layers , activation function , epochs , add dropout layer or add Regularizer according to the need .
- Evaluation Step
- Prediction


# Load Data:
[Click Here to Download DataSet](https://github.com/ramsha275/ML_Datasets/blob/main/compresive_strength_concrete.csv)

In [24]:
import numpy as np
import pandas as pd
import tensorflow as tf
import seaborn as sns
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam, SGD

In [25]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [26]:
data = pd.read_csv('/content/gdrive/MyDrive/compresive_strength_concrete.csv')

In [27]:
data.shape

(1030, 9)

In [28]:
data.head()

Cement (component 1)(kg in a m^3 mixture)  ...  Concrete compressive strength(MPa, megapascals) 
0                                      540.0  ...                                             79.99
1                                      540.0  ...                                             61.89
2                                      332.5  ...                                             40.27
3                                      332.5  ...                                             41.05
4                                      198.6  ...                                             44.30

[5 rows x 9 columns]

##Checking Missing Values ( If Exist ; Fill each record with mean of its feature )

In [29]:
data.isnull().sum()

Cement (component 1)(kg in a m^3 mixture)                0
Blast Furnace Slag (component 2)(kg in a m^3 mixture)    0
Fly Ash (component 3)(kg in a m^3 mixture)               0
Water  (component 4)(kg in a m^3 mixture)                0
Superplasticizer (component 5)(kg in a m^3 mixture)      0
Coarse Aggregate  (component 6)(kg in a m^3 mixture)     0
Fine Aggregate (component 7)(kg in a m^3 mixture)        0
Age (day)                                                0
Concrete compressive strength(MPa, megapascals)          0
dtype: int64

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column                                                 Non-Null Count  Dtype  
---  ------                                                 --------------  -----  
 0   Cement (component 1)(kg in a m^3 mixture)              1030 non-null   float64
 1   Blast Furnace Slag (component 2)(kg in a m^3 mixture)  1030 non-null   float64
 2   Fly Ash (component 3)(kg in a m^3 mixture)             1030 non-null   float64
 3   Water  (component 4)(kg in a m^3 mixture)              1030 non-null   float64
 4   Superplasticizer (component 5)(kg in a m^3 mixture)    1030 non-null   float64
 5   Coarse Aggregate  (component 6)(kg in a m^3 mixture)   1030 non-null   float64
 6   Fine Aggregate (component 7)(kg in a m^3 mixture)      1030 non-null   float64
 7   Age (day)                                              1030 non-null   int64  
 8   Concrete compressive strength(MPa, megapascals)  

In [31]:
# Separating Input and Output Colmumns 
X = data.iloc[:, :-1].values  # Input Columns
Y = data.iloc[:, -1:].values # Output Columns 

In [32]:
X

array([[ 540. ,    0. ,    0. , ..., 1040. ,  676. ,   28. ],
       [ 540. ,    0. ,    0. , ..., 1055. ,  676. ,   28. ],
       [ 332.5,  142.5,    0. , ...,  932. ,  594. ,  270. ],
       ...,
       [ 148.5,  139.4,  108.6, ...,  892.4,  780. ,   28. ],
       [ 159.1,  186.7,    0. , ...,  989.6,  788.9,   28. ],
       [ 260.9,  100.5,   78.3, ...,  864.5,  761.5,   28. ]])

In [33]:
Y

array([[79.99],
       [61.89],
       [40.27],
       ...,
       [23.7 ],
       [32.77],
       [32.4 ]])

# Splitting Data 
###Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).

In [34]:
def split_train_val_test(x, y, train, val, test):
    x_rows, x_col = x.shape
    y_rows, y_col = y.shape 
    
    train_start = 0
    train_stop = int(x_rows*train)
    
    val_start = train_stop
    val_stop = int(x_rows*train)+int(x_rows*val)
    
    test_start = val_stop
    test_stop = None

    x_train = x[train_start:train_stop,] # Extracting X_Training Data 
    x_val = x[val_start:val_stop,]
    x_test = x[test_start:test_stop]
    
    y_train = y[train_start:train_stop,] # Extracting y_Training Data 
    y_val = y[val_start:val_stop,]
    y_test = y[test_start:test_stop]
    
    #Splitting Desicription 
    desc = f'''Splitting Discription:
    Training Data {int(train*100)}%
    Validation Data {int(val*100)}%
    Testing Data {int(val*100)}%
    
    Shape of Training Data {x.shape}
    Shape of Target Data {y.shape}
    
    Shape of x_train {x_train.shape}
    Shape of x_val {x_val.shape}
    Shape of x_test {x_test.shape}
     
    Shape of y_train {y_train.shape}
    Shape of y_val {y_val.shape}
    Shape of y_test {y_test.shape}
    
    '''
    
    return x_train, x_val, x_test, y_train, y_val, y_test, desc



x_train, x_val, x_test, y_train, y_val, y_test, desc = split_train_val_test(X,Y,.5,.3,.2)
print (desc)


Splitting Discription:
    Training Data 50%
    Validation Data 30%
    Testing Data 30%
    
    Shape of Training Data (1030, 8)
    Shape of Target Data (1030, 1)
    
    Shape of x_train (515, 8)
    Shape of x_val (309, 8)
    Shape of x_test (206, 8)
     
    Shape of y_train (515, 1)
    Shape of y_val (309, 1)
    Shape of y_test (206, 1)
    
    


In [35]:
print (x_train.shape, x_test.shape, x_val.shape)
print (y_train.shape, y_test.shape, y_val.shape)

(515, 8) (206, 8) (309, 8)
(515, 1) (206, 1) (309, 1)


# Standardization of Training / Test / Validation Data 

In [36]:
mean = x_train.mean(axis=0)
x_train -= mean
std = x_train.std(axis=0)
x_train /= std


x_val -= mean
x_val /= std

x_test -= mean
x_test /= std



In [37]:
print (x_train.shape, x_test.shape, x_val.shape)
print (y_train.shape, y_test.shape, y_val.shape)

(515, 8) (206, 8) (309, 8)
(515, 1) (206, 1) (309, 1)


# Setting up the model

In [38]:
model = Sequential()
model.add(tf.keras.layers.Dense(10, activation='relu',input_shape=(8,)))
model.add(tf.keras.layers.Dense(8,))
model.add(tf.keras.layers.Dense(6,))
model.add(tf.keras.layers.Dense(1,))

# Model Compilation

In [39]:
model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])

# Training

In [40]:
history = model.fit(x_train, y_train,epochs=200, validation_data =(x_val, y_val))

Epoch 1/200
17/17 [==============================] - 1s 12ms/step - loss: 2021.6575 - mae: 41.6399 - val_loss: 867.2118 - val_mae: 25.7580
Epoch 2/200
17/17 [==============================] - 0s 5ms/step - loss: 1929.1453 - mae: 40.5521 - val_loss: 834.5218 - val_mae: 25.1078
Epoch 3/200
17/17 [==============================] - 0s 4ms/step - loss: 1948.3245 - mae: 40.6870 - val_loss: 795.9290 - val_mae: 24.3118
Epoch 4/200
17/17 [==============================] - 0s 5ms/step - loss: 1830.7469 - mae: 39.0295 - val_loss: 751.3867 - val_mae: 23.3742
Epoch 5/200
17/17 [==============================] - 0s 4ms/step - loss: 1803.1514 - mae: 38.4036 - val_loss: 701.8964 - val_mae: 22.2824
Epoch 6/200
17/17 [==============================] - 0s 4ms/step - loss: 1596.6580 - mae: 36.2809 - val_loss: 647.8570 - val_mae: 21.0688
Epoch 7/200
17/17 [==============================] - 0s 4ms/step - loss: 1512.3279 - mae: 34.9152 - val_loss: 588.8571 - val_mae: 19.7230
Epoch 8/200
17/17 [==============

# Evaluation on Test Data

In [41]:

loss, mae = model.evaluate(x_test, y_test)


7/7 [==============================] - 0s 2ms/step - loss: 226.2671 - mae: 11.6562


In [42]:
loss, mae

(226.26712036132812, 11.656214714050293)

#Prediction

In [43]:
pred = model.predict(x_test[0:5])
pred

array([[27.01664 ],
       [43.323128],
       [43.993305],
       [61.59108 ],
       [63.595345]], dtype=float32)